name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["22", "24", "26"]
    name: Test with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node }}
      - name: Installing dependencies
        run: npm ci
      - name: Linting
        run: npm run lint:all
      - name: Testing
        run: npm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Publishing
        run: npm publish --ignore-scripts
